import javax.swing.*;
public class InquryForm {
    public static void main(String[] args) {
        JFrame f = new JFrame("Inquiry Form");
        JLabel l1 = new JLabel("INQURY FORM");
        l1.setBounds(500,0,100,15);
        f.add(l1);
        JLabel l2 = new JLabel("DiSHA");
        l2.setBounds(10, 0, 100, 50);
        f.add(l2);
        JLabel l3 = new JLabel("COMPUTER INSTITUE");
        l3.setBounds(0, 10, 200, 50);
        f.add(l3);
        JLabel no = new JLabel("No:");
        no.setBounds(860, 20, 60, 50);
        f.add(no);
        JTextArea no1 = new JTextArea();
        no1.setBounds(880,40,80,20);
        f.add(no1);
        JLabel DateofInquire = new JLabel("Date  of  Inquire  :");
        DateofInquire.setBounds(0,50,220,70);
        f.add(DateofInquire);
        JTextArea DateofInquirearea = new JTextArea();
        DateofInquirearea.setBounds(100,80,400,20);
        f.add(DateofInquirearea);
        JLabel Name = new JLabel("Name  :");
        Name.setBounds(0,60,80,150);
        f.add(Name);
        JTextArea Namearea = new JTextArea();
        Namearea.setBounds(50,130,500,20);
        f.add(Namearea);
        JLabel FName,SName,LName;
        FName = new JLabel("First  Name");
        SName = new JLabel("Second  Name");
        LName = new JLabel("Last  Name");
        FName.setBounds(60, 140, 100, 40);
        SName.setBounds(230,140,450,40);
        LName.setBounds(450,140,160,40);
        f.add(FName);f.add(SName);f.add(LName);
        JLabel addres = new JLabel("Address  :");
        addres.setBounds(0,160,100,60);
        f.add(addres);
        JTextArea addresArea = new JTextArea();
        addresArea.setBounds(60,180,500,39);
        f.add(addresArea);
        JLabel contactNo = new JLabel("Contact  No  :");
        contactNo.setBounds(0,210,100,80);
        f.add(contactNo);
        JTextArea ContactNo = new JTextArea();
        ContactNo.setBounds(80,240,500,20);
        f.add(ContactNo);
        JLabel Residence,Mobile;
        Residence = new JLabel("Ressidence");
        Mobile = new JLabel("Mobile");
        Residence.setBounds(100,250,100,40);
        Mobile.setBounds(420,250,100,40);
        f.add(Residence);f.add(Mobile);
        JLabel Emailid = new JLabel("E - mail  id  :");
        Emailid.setBounds(0,250,150,100);
        f.add(Emailid);
        JTextArea Emailidarea = new JTextArea();
        Emailidarea.setBounds(70,290,400,20);
        f.add(Emailidarea);
        JLabel DateofBirth = new JLabel("Date  of  Birth  :");
        DateofBirth.setBounds(0,280,100,110);
        f.add(DateofBirth);
        JTextArea DateofBirtharea = new JTextArea();
        DateofBirtharea.setBounds(90,325,120,20);
        f.add(DateofBirtharea);
        JLabel Qualification = new JLabel("Qualification  :");
        Qualification.setBounds(220,275,100,120);
        f.add(Qualification);
        JTextArea Qualificationarea = new JTextArea();
        Qualificationarea.setBounds(310,325,280,20);
        f.add(Qualificationarea);
        JLabel PreviousKnowledgeOfComputer = new JLabel("Previous  Knowledge  Of  Computer  :");
        PreviousKnowledgeOfComputer.setBounds(0,300,220,140);
        f.add(PreviousKnowledgeOfComputer);
        JLabel yesno = new JLabel("YES  /  No");
        yesno.setBounds(400,300,100,140);
        f.add(yesno);
        JLabel IfYes = new JLabel("If  Yes  Please  Specify  :");
        IfYes.setBounds(0,335,220,140);
        f.add(IfYes);
        JTextArea IfYesarea = new JTextArea();
        IfYesarea.setBounds(140,395,450,20);
        f.add(IfYesarea);
        JLabel HowYouKnow = new JLabel("How  You  Know  About  DiSHA  : 1 . Student [ ]  2 . Holding [ ] 3 . Newspaper [ ] 4 . Other ");
        HowYouKnow.setBounds(0,350,500,160);
        f.add(HowYouKnow);
        JTextArea HowYouKnowarea = new JTextArea();
        HowYouKnowarea.setBounds(490,423,200,20);
        f.add(HowYouKnowarea);
        JLabel InterestedIn = new JLabel("Interested  in  :");
        InterestedIn.setBounds(0,405,200,100);
        f.add(InterestedIn);
        JTextArea InterestedInarea = new JTextArea();
        InterestedInarea.setBounds(90,450,500,20);
        f.add(InterestedInarea);
        JLabel BatchTiming = new JLabel("Batch  &  Timing  :");
        BatchTiming.setBounds(0,430,210,110);
        f.add(BatchTiming);
        JTextArea BatchTimingarea = new JTextArea();
        BatchTimingarea.setBounds(110,480,500,20);
        f.add(BatchTimingarea);
        JLabel Refrences = new JLabel("REFERENCES");
        Refrences.setBounds(500,450,100,120);
        f.add(Refrences);
        String data[][]={{"Name :","Name : "},
        {"Relation","Relation"},
        {"Contact No :","Contact No :"},
        {"Address :","Address :"},
        {"Qualification :","Qualification"}};
        String column[]={" "," "};
        JTable s=new JTable(data,column);
        s.setBounds(0,430,600,80);
        JScrollPane p=new JScrollPane(s);
        f.add(p);
        f.setSize(1000,1200);
        f.setLayout(null);
        f.setVisible(true);
    }
}
